### ISSUE TITLE
100% test coverage in packages

### ISSUE THREAD

**Issue by gianfrancopapa** [gianfrancopapa/bricks#26]
- [ ] api_client

![Image](https://github.com/gianfrancopapa/bricks/assets/98348115/ed7dfa73-4016-4e8d-b8d1-48ee7365c01f)

- [ ] auth_client

![Image](https://github.com/gianfrancopapa/bricks/assets/98348115/0b2ce3e8-5bca-4ec1-9b5c-fd6956beaef7)

- [ ] form_inputs

![Image](https://github.com/gianfrancopapa/bricks/assets/98348115/359c7866-985d-4135-9281-d187aa2cde75)

- [X] token_provider
- [ ] ui_package (currently no tests)
- [ ] gallery (currently no tests)
- [ ] users_repository

![Image](https://github.com/gianfrancopapa/bricks/assets/98348115/7aae5c55-1a5b-4f51-bc27-2300ba7726b5)

**Comment by anfernandezz** [comment]
@gianfrancopapa ui_package and gallery should have 100% coverage as well?
