### ISSUE TITLE
The named parameter 'colorFilter' isn't defined

### ISSUE THREAD

**Issue by fleeser** [gianfrancopapa/bricks#6]
Hey! 👋 
First of all: Thanks for your awesome work!

I wanted to try out the new release of **ui_package** (0.4.0) today.
After running the generator, there is a file called `assets.gen.dart` inside of `lib/src/generated/` that contains the following error:

> The named parameter 'colorFilter' isn't defined.
> Try correcting the name to an existing named parameter's name, or defining a named parameter with the name 'colorFilter'.

This is for the named constructor `SvgPicture.asset`.

**Comment by gianfrancopapa** [comment]
Hey @fleeser! Could you tell me which version of Flutter and mason are you using? 
I updated the brick recently because of a similar error, but I want to be sure first :)

**Comment by fleeser** [comment]
mason_cli 0.1.0-dev.50
flutter >=3.3.0
